import fromDot from 'ngraph.fromdot';
export default function getGraph() {
  return fromDot(`digraph G {
"Normal gets you nowhere" -> "Ordinary is the enemy of extraordinary."
"Normal gets you nowhere" -> "Average is the enemy of awesome."
"Normal gets you nowhere" -> "Mediocrity will never do."
"Normal gets you nowhere" -> "Comfort is the enemy of achievement."
"Normal gets you nowhere" -> "The road to success is not for the faint of heart."
"Normal gets you nowhere" -> "Greatness is not a function of circumstance, but of choice."
"Normal gets you nowhere" -> "If you want to be exceptional, you can't be normal."
"Normal gets you nowhere" -> "Normalcy is the antithesis of progress."
"Normal gets you nowhere" -> "To stand out, you must step out of line."
"Normal gets you nowhere" -> "Extraordinary begins where normal ends."
"Ordinary is the enemy of extraordinary." -> "Success is not final, failure is not fatal: it is the courage to continue that counts."
"Ordinary is the enemy of extraordinary." -> "The only way to do great work is to love what you do."
"Ordinary is the enemy of extraordinary." -> "Be the change you wish to see in the world."
"Ordinary is the enemy of extraordinary." -> "Life is what happens to you while you're busy making other plans."
"Ordinary is the enemy of extraordinary." -> "The future belongs to those who believe in the beauty of their dreams."
"Ordinary is the enemy of extraordinary." -> "Don't watch the clock; do what it does. Keep going."
"Ordinary is the enemy of extraordinary." -> "The only limit to our realization of tomorrow will be our doubts of today."
"Ordinary is the enemy of extraordinary." -> "It does not matter how slowly you go as long as you do not stop."
"Ordinary is the enemy of extraordinary." -> "Strive not to be a success, but rather to be of value."
"Ordinary is the enemy of extraordinary." -> "The best way to predict the future is to create it."
"Average is the enemy of awesome." -> "Mediocrity is the enemy of greatness."
"Average is the enemy of awesome." -> "Good is the enemy of great."
"Average is the enemy of awesome." -> "Perfection is the enemy of progress."
"Average is the enemy of awesome." -> "Normal is the enemy of extraordinary."
"Average is the enemy of awesome." -> "Comfort is the enemy of achievement."
"Average is the enemy of awesome." -> "Ordinary is the enemy of exceptional."
"Average is the enemy of awesome." -> "Settling is the enemy of success."
"Average is the enemy of awesome." -> "Complacency is the enemy of excellence."
"Average is the enemy of awesome." -> "Conformity is the enemy of innovation."
"Average is the enemy of awesome." -> "Status quo is the enemy of growth."
"Mediocrity will never do." -> "\\"Mediocrity will never do. You are capable of something better.\\" - Gordon B. Hinckley"
"Mediocrity will never do." -> "\\"The height of mediocrity is still low.\\" - Vanna Bonta"
"Mediocrity will never do." -> "\\"There is a real magic in enthusiasm. It spells the difference between mediocrity and accomplishment.\\" - Norman Vincent Peale"
"Mediocrity will never do." -> "\\"Only mediocrity can be trusted to be always at its best.\\" - Max Beerbohm"
"Mediocrity will never do." -> "\\"There's a lot to be said for doing what you're not supposed to do, and the rewards of doing what you're supposed to do are more subtle and take longer to become apparent, which maybe makes it less attractive. But your life is the blueprint you make after the building is built.\\" - Richard Ford"
"Mediocrity will never do." -> "\\"The only way to escape the corruptible effect of praise is to go on working.\\" - Albert Einstein"
"Mediocrity will never do." -> "\\"Mediocrity knows nothing higher than itself; but talent instantly recognizes genius.\\" - Arthur Conan Doyle"
"Mediocrity will never do." -> "\\"In the republic of mediocrity, genius is dangerous.\\" - Robert Green Ingersoll"
"Mediocrity will never do." -> "\\"The difference between greatness and mediocrity is often how an individual views a mistake.\\" - Nelson Boswell"
"Mediocrity will never do." -> "\\"Great spirits have always encountered violent opposition from mediocre minds.\\" - Albert Einstein"
"Comfort is the enemy of achievement." -> "Success is not final, failure is not fatal: it is the courage to continue that counts."
"Comfort is the enemy of achievement." -> "The only way to do great work is to love what you do."
"Comfort is the enemy of achievement." -> "The harder you work, the luckier you get."
"Comfort is the enemy of achievement." -> "Strive not to be a success, but rather to be of value."
"Comfort is the enemy of achievement." -> "The only place where success comes before work is in the dictionary."
"Comfort is the enemy of achievement." -> "Success is walking from failure to failure with no loss of enthusiasm."
"Comfort is the enemy of achievement." -> "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will."
"Comfort is the enemy of achievement." -> "I find that the harder I work, the more luck I seem to have."
"Comfort is the enemy of achievement." -> "There are no secrets to success. It is the result of preparation, hard work, and learning from failure."
"Comfort is the enemy of achievement." -> "Success is not how high you have climbed, but how you make a positive difference to the world."
"The road to success is not for the faint of heart." -> "Success is not final, failure is not fatal: it is the courage to continue that counts."
"The road to success is not for the faint of heart." -> "The only place where success comes before work is in the dictionary."
"The road to success is not for the faint of heart." -> "Success is not the key to happiness. Happiness is the key to success."
"The road to success is not for the faint of heart." -> "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will."
"The road to success is not for the faint of heart." -> "Success is walking from failure to failure with no loss of enthusiasm."
"The road to success is not for the faint of heart." -> "I find that the harder I work, the more luck I seem to have."
"The road to success is not for the faint of heart." -> "There are no secrets to success. It is the result of preparation, hard work, and learning from failure."
"The road to success is not for the faint of heart." -> "Success is not how high you have climbed, but how you make a positive difference to the world."
"The road to success is not for the faint of heart." -> "The secret of success is to do the common things uncommonly well."
"The road to success is not for the faint of heart." -> "Success is not in what you have, but who you are."
"Greatness is not a function of circumstance, but of choice." -> "Greatness lies not in being strong, but in the right using of strength."
"Greatness is not a function of circumstance, but of choice." -> "The measure of a man is what he does with power."
"Greatness is not a function of circumstance, but of choice." -> "The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge and controversy."
"Greatness is not a function of circumstance, but of choice." -> "It's not the size of the dog in the fight, it's the size of the fight in the dog."
"Greatness is not a function of circumstance, but of choice." -> "Destiny is not a matter of chance; it is a matter of choice. It is not a thing to be waited for, it is a thing to be achieved."
"Greatness is not a function of circumstance, but of choice." -> "The heights by great men reached and kept were not attained by sudden flight, but they, while their companions slept, were toiling upward in the night."
"Greatness is not a function of circumstance, but of choice." -> "Great spirits have always encountered violent opposition from mediocre minds."
"Greatness is not a function of circumstance, but of choice." -> "To be great is to be misunderstood."
"Greatness is not a function of circumstance, but of choice." -> "The price of greatness is responsibility."
"Greatness is not a function of circumstance, but of choice." -> "The greatest glory in living lies not in never falling, but in rising every time we fall."
"If you want to be exceptional, you can't be normal." -> "\\"To be great is to be misunderstood.\\" - Ralph Waldo Emerson"
"If you want to be exceptional, you can't be normal." -> "\\"The person who follows the crowd will usually go no further than the crowd.\\" - Albert Einstein"
"If you want to be exceptional, you can't be normal." -> "\\"Conformity is the jailer of freedom and the enemy of growth.\\" - John F. Kennedy"
"If you want to be exceptional, you can't be normal." -> "\\"The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself. Therefore, all progress depends on the unreasonable man.\\" - George Bernard Shaw"
"If you want to be exceptional, you can't be normal." -> "\\"Here's to the crazy ones. The misfits. The rebels. The troublemakers.\\" - Apple Inc."
"If you want to be exceptional, you can't be normal." -> "\\"Do not go where the path may lead, go instead where there is no path and leave a trail.\\" - Ralph Waldo Emerson"
"If you want to be exceptional, you can't be normal." -> "\\"The individual has always had to struggle to keep from being overwhelmed by the tribe.\\" - Friedrich Nietzsche"
"If you want to be exceptional, you can't be normal." -> "\\"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.\\" - Ralph Waldo Emerson"
"If you want to be exceptional, you can't be normal." -> "\\"Whenever you find yourself on the side of the majority, it is time to pause and reflect.\\" - Mark Twain"
"If you want to be exceptional, you can't be normal." -> "\\"The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.\\" - Albert Camus"
"Normalcy is the antithesis of progress." -> "\\"The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man.\\" - George Bernard Shaw"
"Normalcy is the antithesis of progress." -> "\\"Progress is impossible without change, and those who cannot change their minds cannot change anything.\\" - George Bernard Shaw"
"Normalcy is the antithesis of progress." -> "\\"All progress has resulted from people who took unpopular positions.\\" - Adlai Stevenson"
"Normalcy is the antithesis of progress." -> "\\"The greatest enemy of progress is not stagnation, but false progress.\\" - Sydney J. Harris"
"Normalcy is the antithesis of progress." -> "\\"Comfort is the enemy of progress.\\" - P.T. Barnum"
"Normalcy is the antithesis of progress." -> "\\"If you're not failing every now and again, it's a sign you're not doing anything very innovative.\\" - Woody Allen"
"Normalcy is the antithesis of progress." -> "\\"The only way to discover the limits of the possible is to go beyond them into the impossible.\\" - Arthur C. Clarke"
"Normalcy is the antithesis of progress." -> "\\"Progress lies not in enhancing what is, but in advancing toward what will be.\\" - Khalil Gibran"
"Normalcy is the antithesis of progress." -> "\\"The world hates change, yet it is the only thing that has brought progress.\\" - Charles Kettering"
"Normalcy is the antithesis of progress." -> "\\"All progress is precarious, and the solution of one problem brings us face to face with another problem.\\" - Martin Luther King Jr."
"To stand out, you must step out of line." -> "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment."
"To stand out, you must step out of line." -> "The person who follows the crowd will usually go no further than the crowd."
"To stand out, you must step out of line." -> "Conformity is the jailer of freedom and the enemy of growth."
"To stand out, you must step out of line." -> "The individual has always had to struggle to keep from being overwhelmed by the tribe."
"To stand out, you must step out of line." -> "Be a voice, not an echo."
"To stand out, you must step out of line." -> "The nail that sticks out gets hammered down."
"To stand out, you must step out of line." -> "To be normal is the ideal aim of the unsuccessful."
"To stand out, you must step out of line." -> "The opposite of courage in our society is not cowardice, it is conformity."
"To stand out, you must step out of line." -> "The reward for conformity is that everyone likes you but yourself."
"Extraordinary begins where normal ends." -> "Greatness begins at the end of your comfort zone."
"Extraordinary begins where normal ends." -> "Excellence is not a destination; it's a continuous journey that never ends."
"Extraordinary begins where normal ends." -> "The difference between ordinary and extraordinary is that little extra."
"Extraordinary begins where normal ends." -> "When you reach the end of your rope, tie a knot in it and hang on."
"Extraordinary begins where normal ends." -> "Normal is not something to aspire to, it's something to get away from."
"Extraordinary begins where normal ends." -> "The only way to do great work is to love what you do."
"Extraordinary begins where normal ends." -> "If you want something you've never had, you must be willing to do something you've never done."
"Extraordinary begins where normal ends." -> "Success is not final, failure is not fatal: it is the courage to continue that counts."
"Extraordinary begins where normal ends." -> "The moment you're ready to quit is usually the moment right before a miracle happens."
"Extraordinary begins where normal ends." -> "Don't be afraid to give up the good to go for the great."
"To stand out, you must step out of line." -> "Be a first-rate version of yourself, not a second-rate version of someone else."
"To stand out, you must step out of line." -> "If you don't build your dream, someone else will hire you to help them build theirs."
"To stand out, you must step out of line." -> "The opposite of courage in our society is not cowardice, it's conformity."
"To stand out, you must step out of line." -> "Don't be afraid to stand for what you believe in, even if that means standing alone."
}`);
}