const emotionsMatrix = [
  ["Joy", "Elation", "Ecstasy", "Rapture", "Bliss", "Euphoria", "Eagerness", "Enthusiasm", "Excitement", "Passion"],
  ["Serenity", "Tranquility", "Peace", "Calm", "Contentment", "Satisfaction", "Relaxation", "Comfort", "Safety", "Satisfaction"],
  ["Surprise", "Interest", "Anticipation", "Hope", "Optimism", "Confidence", "Boldness", "Courage", "Inspiration", "Optimism"],
  ["Fear", "Apprehension", "Worry", "Anxiety", "Unease", "Discomfort", "Distress", "Anguish", "Agony", "Terror"],
  ["Gratitude", "Love", "Affection", "Tenderness", "Fondness", "Sentimentality", "Nostalgia", "Reminiscence", "Appreciation", "Adoration"],
  ["Anger", "Annoyance", "Irritation", "Exasperation", "Frustration", "Impatience", "Pique", "Resentment", "Envy", "Rage"],
  ["Sadness", "Melancholy", "Loneliness", "Nostalgia", "Gloom", "Sorrow", "Grief", "Woe", "Misery", "Despondency"],
  ["Disgust", "Loathing", "Abhorrence", "Scorn", "Contempt", "Revulsion", "Disapproval", "Dislike", "Hatred", "Loathing"],
  ["Amusement", "Pleasure", "Delight", "Glee", "Cheer", "Happiness", "Mirth", "Joyfulness", "Jubilation", "Elation"],
  ["Guilt", "Remorse", "Regret", "Self-reproach", "Shame", "Humiliation", "Embarrassment", "Disgrace", "Mortification", "Contrition"]
];

const emotionsList = ['acceptance', 'admiration', 'adoration', 'affection', 'afraid', 'agitation', 'agony', 'aggressive', 'alarm', 'alarmed', 'alienation', 'amazement', 'ambivalence', 'amusement', 'anger', 'anguish', 'annoyed', 'anticipating', 'anxious', 'apathy', 'apprehension', 'arrogant', 'assertive', 'astonished', 'attentiveness', 'attraction', 'aversion', 'awe', 'baffled', 'bewildered', 'bitter', 'bitter sweetness', 'bliss', 'bored', 'brazen', 'brooding', 'calm', 'carefree', 'careless', 'caring', 'charity', 'cheeky', 'cheerfulness', 'claustrophobic', 'coercive', 'comfortable', 'confident', 'confusion', 'contempt', 'content', 'courage', 'cowardly', 'cruelty', 'curiosity', 'cynicism', 'dazed', 'dejection', 'delighted', 'demoralized', 'depressed', 'desire', 'despair', 'determined', 'disappointment', 'disbelief', 'discombobulated', 'discomfort', 'discontentment', 'disgruntled', 'disgust', 'disheartened', 'dislike', 'dismay', 'disoriented', 'dispirited', 'displeasure', 'distraction', 'distress', 'disturbed', 'dominant', 'doubt', 'dread', 'driven', 'dumbstruck', 'eagerness', 'ecstasy', 'elation', 'embarrassment', 'empathy', 'enchanted', 'enjoyment', 'enlightened', 'ennui', 'enthusiasm', 'envy', 'epiphany', 'euphoria', 'exasperated', 'excitement', 'expectancy', 'fascination', 'fear', 'flakey', 'focused', 'fondness', 'friendliness', 'fright', 'frustrated', 'fury', 'glee', 'gloomy', 'glumness', 'gratitude', 'greed', 'grief', 'grouchiness', 'grumpiness', 'guilt', 'happiness', 'hate', 'hatred', 'helpless', 'homesickness', 'hope', 'hopeless', 'horrified', 'hospitable', 'humiliation', 'humility', 'hurt', 'hysteria', 'idleness', 'impatient', 'indifference', 'indignant', 'infatuation', 'infuriated', 'insecurity', 'insightful', 'insulted', 'interest', 'intrigued', 'irritated', 'isolated', 'jealousy', 'joviality', 'joy', 'jubilation', 'kind', 'lazy', 'liking', 'loathing', 'lonely', 'longing', 'loopy', 'love', 'lust', 'mad', 'melancholy', 'miserable', 'miserliness', 'mixed up', 'modesty', 'moody', 'mortified', 'mystified', 'nasty', 'nauseated', 'negative', 'neglect', 'nervous', 'nostalgic', 'numb', 'obstinate', 'offended', 'optimistic', 'outrage', 'overwhelmed', 'panicked', 'paranoid', 'passion', 'patience', 'pensiveness', 'perplexed', 'persevering', 'pessimism', 'pity', 'pleased', 'pleasure', 'politeness', 'positive', 'possessive', 'powerless', 'pride', 'puzzled', 'rage', 'rash', 'rattled', 'regret', 'rejected', 'relaxed', 'relieved', 'reluctant', 'remorse', 'resentment', 'resignation', 'restlessness', 'revulsion', 'ruthless', 'sadness', 'satisfaction', 'scared', 'schadenfreude', 'scorn', 'self-caring', 'self-compassionate', 'self-confident', 'self-conscious', 'self-critical', 'self-loathing', 'self-motivated', 'self-pity', 'self-respecting', 'self-understanding', 'sentimentality', 'serenity', 'shame', 'shameless', 'shocked', 'smug', 'sorrow', 'spite', 'stressed', 'strong', 'stubborn', 'stuck', 'submissive', 'suffering', 'sullenness', 'surprise', 'suspense', 'suspicious', 'sympathy', 'tenderness', 'tension', 'terror', 'thankfulness', 'thrilled', 'tired', 'tolerance', 'torment', 'triumphant', 'troubled', 'trust', 'uncertainty', 'undermined', 'uneasiness', 'unhappy', 'unnerved', 'unsettled', 'unsure', 'upset', 'vengeful', 'vicious', 'vigilance', 'vulnerable', 'weak', 'woe', 'worried', 'worthy', 'wrath']


// List 100 emotions as a javascript array, where each emotion has `name`, `description`,
//  and a few numerical metrics to sort emotions. Such as `energy`, `pleasantness`, 
// `approach vs avoidance`, `self vs other focused`, `activation vs deactivation`, `cognition vs affect`
const emotions = [
  {
      name: "Joy",
      description: "A feeling of great pleasure and happiness.",
      energy: 8,
      pleasantness: 9,
      approach_avoidance: 9,
      self_other_focused: 7,
      activation_deactivation: 8,
      cognition_affect: 7
  },
  {
      name: "Elation",
      description: "A feeling of great happiness and triumph.",
      energy: 9,
      pleasantness: 9,
      approach_avoidance: 9,
      self_other_focused: 7,
      activation_deactivation: 9,
      cognition_affect: 7
  },
  {
      name: "Ecstasy",
      description: "A feeling of intense pleasure and joy.",
      energy: 10,
      pleasantness: 10,
      approach_avoidance: 9,
      self_other_focused: 7,
      activation_deactivation: 10,
      cognition_affect: 7
  },
  {
      name: "Rapture",
      description: "A feeling of intense pleasure and happiness.",
      energy: 9,
      pleasantness: 10,
      approach_avoidance: 9,
      self_other_focused: 7,
      activation_deactivation: 9,
      cognition_affect: 7
  },
  {
      name: "Bliss",
      description: "A feeling of perfect happiness and contentment.",
      energy: 8,
      pleasantness: 10,
      approach_avoidance: 9,
      self_other_focused: 7,
      activation_deactivation: 8,
      cognition_affect: 7
  },
  {
      name: "Euphoria",
      description: "A feeling of great happiness and well-being.",
      energy: 9,
      pleasantness: 9,
      approach_avoidance: 9,
      self_other_focused: 7,
      activation_deactivation: 9,
      cognition_affect: 7
  },
  {
      name: "Eagerness",
      description: "A feeling of keen desire or interest.",
      energy: 8,
      pleasantness: 8,
      approach_avoidance: 9,
      self_other_focused: 7,
      activation_deactivation: 8,
      cognition_affect: 7
  },
  {
      name: "Enthusiasm",
      description: "A feeling of great excitement and interest.",
      energy: 9,
      pleasantness: 8,
      approach_avoidance: 9,
      self_other_focused: 7,
      activation_deactivation: 9,
      cognition_affect: 7
  },
    {
        name: "Excitement",
        description: "A feeling of great enthusiasm and energy.",
        energy: 10,
        pleasantness: 8,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 10,
        cognition_affect: 7
    },
    {
        name: "Passion",
        description: "A strong feeling of enthusiasm or excitement for something.",
        energy: 9,
        pleasantness: 8,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 9,
        cognition_affect: 7
    },
    {
        name: "Serenity",
        description: "A feeling of calm and peacefulness.",
        energy: 4,
        pleasantness: 9,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 4,
        cognition_affect: 7
    },
    {
        name: "Tranquility",
        description: "A feeling of calm and peacefulness.",
        energy: 3,
        pleasantness: 9,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 3,
        cognition_affect: 7
    },
    {
        name: "Peace",
        description: "A feeling of calm and quiet.",
        energy: 2,
        pleasantness: 9,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 2,
        cognition_affect: 7
    },
    {
        name: "Calm",
        description: "A feeling of peacefulness and composure.",
        energy: 1,
        pleasantness: 9,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 1,
        cognition_affect: 7
    },
    {
        name: "Contentment",
        description: "A feeling of satisfaction and happiness with one's situation.",
        energy: 4,
        pleasantness: 8,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 4,
        cognition_affect: 7
    },
    {
        name: "Satisfaction",
        description: "A feeling of pleasure and contentment.",
        energy: 3,
        pleasantness: 8,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 3,
        cognition_affect: 7
    },
    {
        name: "Relaxation",
        description: "A feeling of calm and ease.",
        energy: 2,
        pleasantness: 8,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 2,
        cognition_affect: 7
    },
    {
        name: "Comfort",
        description: "A feeling of ease and security.",
        energy: 1,
        pleasantness: 8,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 1,
        cognition_affect: 7
    },
    {
        name: "Safety",
        description: "A feeling of security and protection.",
        energy: 1,
        pleasantness: 9,
        approach_avoidance: 9,
        self_other_focused: 7,
        activation_deactivation: 1,
        cognition_affect: 7
    },
    {
        name: "Surprise",
        description: "A feeling of mild shock or amazement.",
        energy: 6,
        pleasantness: 5,
        approach_avoidance: 5,
        self_other_focused: 7,
        activation_deactivation: 7,
        cognition_affect: 8
    },
    {
        name: "Interest",
        description: "A feeling of attention and engagement.",
        energy: 6,
        pleasantness: 6,
        approach_avoidance: 6,
        self_other_focused: 7,
        activation_deactivation: 6,
        cognition_affect: 8
    },
    {
        name: "Anticipation",
        description: "A feeling of expectation or excitement about something to come.",
        energy: 7,
        pleasantness: 7,
        approach_avoidance: 8,
        self_other_focused: 7,
        activation_deactivation: 7,
        cognition_affect: 8
    },
    {
        name: "Hope",
        description: "A feeling of expectation and desire for a certain thing to happen.",
        energy: 6,
        pleasantness: 7,
        approach_avoidance: 8,
        self_other_focused: 7,
        activation_deactivation: 6,
        cognition_affect: 8
    },
    {
        name: "Optimism",
        description: "A feeling of hope and confidence about the future.",
        energy: 7,
        pleasantness: 8,
        approach_avoidance: 8,
        self_other_focused: 7,
        activation_deactivation: 7,
        cognition_affect: 8
    },
    {
        name: "Confidence",
        description: "A feeling of trust and belief in oneself.",
        energy: 6,
        pleasantness: 8,
        approach_avoidance: 8,
        self_other_focused: 8,
        activation_deactivation: 6,
        cognition_affect: 8
    },
    {
        name: "Trust",
        description: "A feeling of confidence and reliance in someone or something.",
        energy: 5,
        pleasantness: 8,
        approach_avoidance: 8,
        self_other_focused: 8,
        activation_deactivation: 5,
        cognition_affect: 8
    },
    {
        name: "Love",
        description: "A feeling of strong affection and attachment.",
        energy: 6,
        pleasantness: 9,
        approach_avoidance: 9,
        self_other_focused: 8,
        activation_deactivation: 6,
        cognition_affect: 8
    },
    {
        name: "Affection",
        description: "A feeling of fondness and tenderness.",
        energy: 5,
        pleasantness: 9,
        approach_avoidance: 9,
        self_other_focused: 8,
        activation_deactivation: 5,
        cognition_affect: 8
    }
]

const emotionsByPleasantness = [
    // Positive emotions
    "Adoration",
    "Affection",
    "Appreciation",
    "Benevolence",
    "Bliss",
    "Cheerfulness",
    "Compassion",
    "Contentment",
    "Delight",
    "Empathy",
    "Excitement",
    "Forgiveness",
    "Gratitude",
    "Joy",
    "Kindness",
    "Love",
    "Optimism",
    "Peace",
    "Self-Esteem",
    "Self-Respect",
    "Self-Worth",
    "Serenity",
    "Satisfaction",
    "Tenderness",
    "Thankfulness",
    "Worship",
    // Neutral emotions
    "Amusement",
    "Assertiveness",
    "Boldness",
    "Calm",
    "Caring",
    "Curiosity",
    "Determination",
    "Engagement",
    "Enthusiasm",
    "Euphoria",
    "Expectancy",
    "Involvement",
    "Interest",
    "Perseverance",
    "Pride",
    "Recognition",
    "Relaxation",
    "Resilience",
    "Thrill",
    // Negative emotions
    "Agony",
    "Anguish",
    "Annoyance",
    "Anticipation",
    "Bitter",
    "Confusion",
    "Despair",
    "Disapproval",
    "Disgust",
    "Dislike",
    "Displeasure",
    "Ennui",
    "Exasperation",
    "Fear",
    "Frustration",
    "Grief",
    "Horror",
    "Impatience",
    "Irritation",
    "Loathing",
    "Misery",
    "Outrage",
    "Panic",
    "Pessimism",
    "Rage",
    "Resentment",
    "Revulsion",
    "Sorrow",
    "Sympathy",
    "Terror",
];
